apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sudoku-cli
  annotations:
    github.com/project-slug: dennislwm/sudoku-cli
spec:
  type: other
  lifecycle: unknown
  owner: backstage
