name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        rm -f .coverage
        coverage run --source=sudoku/ -m unittest discover -s tests/
        coverage report -m
        python benchmarks/benchmarks.py
    - name: Check for changes in puzzle.txt
      id: checkfile
      run: |
        echo "::set-output name=changed::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^puzzle.txt$' || echo 'false')"
    - name: Run application
      run: |
        if [[ "${{ steps.checkfile.outputs.changed }}" != "false" ]]; then
          python -m sudoku puzzle.txt | fold -w9 | sed 's/./&|/6' | sed 's/./&|/3' | awk 'NR==7{print "---+---+---"}1' | awk 'NR==4{print "---+---+---"}1' | awk 'NR==1{print "==========="}1'
        fi
